name: speaker
description: Playing audio file
version: 0.0.1
author: sh-ogawa <syogo0417@gmail.com>
homepage: https://github.com/sh-ogawa/speak

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: ooga.sh4.jp.speaker
    pluginClass: SpeakerPlugin